project:
  type: website
  output-dir: docs

website:
  title: "Statistics for Social Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: descriptive.qmd
        text: Descriptive Statistics
      - href: inferential.qmd
        text: Inferential Statistics

format:
  html:
    theme: flatly
    toc: true
