project:
  type: website
  output-dir: docs

website:
  title: "Basic Statistics for Students"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: descriptive.qmd
        text: Descriptive Statistics

format:
  html:
    theme: cosmo
    toc: true
